services:
  - type: web
    name: satellite-map-v4
    env: static
    buildCommand: null
    startCommand: null
    staticPublishPath: ./templates
    routes:
      - type: rewrite
        source: /*
        destination: /satellite_map_v4.html 